### ISSUE TITLE
Required variable "subnets_count" not set

### ISSUE THREAD

**Issue by smith-kyle** [terraform-community-modules/tf_aws_nat#15]
As input I've added every value listed in the README but I'm receiving this error
```
module nat_instance: required variable "name" not set
module nat_instance: required variable "subnets_count" not set
module nat_instance: required variable "vpc_security_group_ids" not set
```

**Comment by smith-kyle** [comment]
was security_groups renamed to `vpc_security_group_ids`?

**Comment by antonbabenko** [comment]
README is outdated, it should say `vpc_security_group_ids`. This module is not very much up-to-date in general. Use it on your own risk. PRs are welcome.
