### ISSUE TITLE
Working with tf_aws_vpc module?

### ISSUE THREAD

**Issue by ashb** [terraform-community-modules/tf_aws_nat#4]
I've got a load of small PRs waiting in the wings in my fork that make this module work alongside the VPC/subnets created by terraform-community-modules/tf_aws_vpc (and thanks to @bobtfish for accepting my PR on AWSnycast) - the changes in a few categories: 
- upgrading terraform features (using `data` sources, converting from CSV to list inputs and outputs)
- removing extra "cruft" from the image unrelated to the functionality (installing puppet for instance); and
- updating the AWSnycast config to find the subnets/route tables created from the tf_aws_vpc module.

I can either open these as small PRs of one-by-one, or I'd be willing to maintain this module too if people are okay with that. What would people prefer?

**Comment by antonbabenko** [comment]
I think we would all benefit if we keep number of similar terraform modules lower, but increase their quality and number of features in some way. Saying that I vote to see smaller PRs and merge them one-by-one here.

**Comment by ashb** [comment]
Cool, I mostly wanted to give a heads up rather than suddenly swamping someone with 8 or so PRs.

**Comment by ashb** [comment]
Right #5 and #6 are good to look at, the other ones are gated behind #5 being merged before I can open those without merge conflicts

**Comment by ashb** [comment]
Okay three more to look at #9 #10 and #11. Once those are merged there is one final one which updates AWSnycast and changes the userdata config to use the tags/names that the tf_aws_vpc module creates.

**Comment by antonbabenko** [comment]
And all 3 looks good to be merged.
